gatling {
  core {
    outputDirectoryBaseName = "linkwave-load"
    directory {
      results = "build/reports/gatling"
    }
  }

  http {
    ahc {
      connectTimeout = 60000
      requestTimeout = 30000
    }
  }
}

linkwave {
  baseUrl = "http://localhost:8080"
  baseUrl = ${?BASE_URL}

  websocketUrl = "ws://localhost:8080/ws"
  websocketUrl = ${?WS_URL}
}
