apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: linkwave
  labels:
    app: linkwave
    component: zookeeper
    tier: messaging
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
