apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: linkwave
  labels:
    app: linkwave
    component: ingress
spec:
  redirectScheme:
    scheme: https
    permanent: true
