apiVersion: v1
kind: Service
metadata:
  name: linkwave-frontend
  namespace: linkwave
  labels:
    app: linkwave
    component: frontend
    tier: application
spec:
  type: ClusterIP
  selector:
    app: linkwave-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
