spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/linkwave}
    username: ${DATABASE_USERNAME:linkwave}
    password: ${DATABASE_PASSWORD:changeme} # pragma: allowlist secret

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:changeme} # pragma: allowlist secret

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: ${MAIL_TLS_ENABLED:false}

# Linkwave custom config for local dev
linkwave:
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    from: no-reply@linkwave.local
    tls-enabled: ${MAIL_TLS_ENABLED:false}
    dev-mode: ${LINKWAVE_MAIL_DEV_MODE:true}
